baseurl: '/'
permalink: pretty
title: 'doctelligence'

logo:
  mobile: "images/logo/logo2.png"
  mobile_height: "106px"  # Increased by 20% from 88px
  mobile_width: "100px"   # Increased by 20% from 83px to better fit the mobile view
  desktop: "images/logo/logo2.png"
  desktop_height: "32px"  # Remains unchanged as it's satisfactory
  desktop_width: "114px"  # Remains unchanged as it's satisfactory

home:
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
